/**
 * The real gmt functions the EDI widgets' unit tests inject as an `EdiLib`,
 * loaded by module path so a test never needs the mount's dynamic imports.
 */
import {
  classifyLocal,
  fromOffsetInstant,
  resolveLocal,
  toOffsetInstant,
} from "@northguild/gmt/instant/convert";
import {
  formatEdifactDate,
  formatEdifactDatePeriod,
  formatEdifactDateTime,
  formatEdifactDateTimePeriod,
  formatEdifactOffsetDateTime,
  formatEdifactTime,
  formatX12Date,
  formatX12DateRange,
  formatX12DateTime,
  formatX12DateTimeRange,
  formatX12Time,
} from "@northguild/gmt/intermodal/format";
import {
  classifyEdifactDtmFormat,
  classifyX12DateTimePeriodFormat,
  classifyX12TimeCode,
  parseEdifactDate,
  parseEdifactDatePeriod,
  parseEdifactDateTime,
  parseEdifactDateTimePeriod,
  parseEdifactOffsetDateTime,
  parseEdifactTime,
  parseX12Date,
  parseX12DateAndTime,
  parseX12DateRange,
  parseX12DateTime,
  parseX12DateTimeRange,
  parseX12Time,
  x12TimeCodeOffset,
  x12TimeCodeZone,
} from "@northguild/gmt/intermodal/parse";
import {
  diffUtcAsDuration,
  maxUtc,
  minUtc,
} from "@northguild/gmt/utc/calculate";
import { isValidTimeZone } from "@northguild/gmt/zoned/validate";
import type { EdiLib } from "~/lib/edi-widgets";

export const lib = {
  classifyEdifactDtmFormat,
  parseEdifactDate,
  parseEdifactTime,
  parseEdifactDateTime,
  parseEdifactOffsetDateTime,
  parseEdifactDatePeriod,
  parseEdifactDateTimePeriod,
  formatEdifactDate,
  formatEdifactTime,
  formatEdifactDateTime,
  formatEdifactOffsetDateTime,
  formatEdifactDatePeriod,
  formatEdifactDateTimePeriod,
  classifyX12DateTimePeriodFormat,
  parseX12Date,
  parseX12Time,
  parseX12DateTime,
  parseX12DateRange,
  parseX12DateTimeRange,
  parseX12DateAndTime,
  formatX12Date,
  formatX12Time,
  formatX12DateTime,
  formatX12DateRange,
  formatX12DateTimeRange,
  classifyX12TimeCode,
  x12TimeCodeOffset,
  x12TimeCodeZone,
  resolveLocal,
  classifyLocal,
  toOffsetInstant,
  fromOffsetInstant,
  isValidTimeZone,
  minUtc,
  maxUtc,
  diffUtcAsDuration,
} as unknown as EdiLib;
